version: '3.8'

include:
  - ./airflow/docker-compose.yml

services:
  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KC_HOSTNAME_URL: http://localhost:8080
    command: 
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
      REACT_APP_KEYCLOAK_URL: http://localhost:8080
      REACT_APP_KEYCLOAK_REALM: reports-realm
      REACT_APP_KEYCLOAK_CLIENT_ID: reports-frontend

  bionicpro-auth:
    image: ${DOCKER_REGISTRY-}bionicproauth
    container_name: bionicpro-auth
    user: "0:0"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
    ports:
      - "7000:8080"
    build:
      context: .
      dockerfile: BionicPro.Auth/Dockerfile
    depends_on:
      - keycloak
    volumes:
      - shared-auth-keys:/app/shared-auth-keys

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    command: --copy-service
    volumes:
      - ./ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom:ro
    environment:
      - LDAP_ORGANISATION=bionicpro
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=admin
    ports:
      - "389:389"

  bionicpro-reports:
    image: ${DOCKER_REGISTRY-}bionicproreports
    container_name: bionicpro-reports
    user: "0:0"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__Reports: "Host=postgres;Database=airflow;Username=airflow;Password=airflow"
    ports:
      - "8000:8080" 
    build:
      context: .
      dockerfile: BionicPro.Reports/Dockerfile
    volumes:
      - shared-auth-keys:/app/shared-auth-keys
    depends_on:
      - postgres 

volumes:
  shared-auth-keys: